use super::LanguageSemantics;

pub static BASH_SEMANTICS: LanguageSemantics = LanguageSemantics {
    language: "bash",

    function_def_kinds: &["function_definition"],
    if_kinds: &["if_statement"],
    loop_kinds: &["for_statement", "while_statement", "c_style_for_statement"],
    variable_declaration_kinds: &["variable_assignment", "declaration_command"],
    assignment_kinds: &["variable_assignment"],
    augmented_assignment_kinds: &[],
    return_kinds: &["return_statement"],
    call_kinds: &["command", "command_substitution"],
    try_catch_kinds: &[],
    throw_kinds: &[],
    string_literal_kinds: &["string", "raw_string", "ansi_c_string"],
    numeric_literal_kinds: &["number"],
    boolean_literal_kinds: &[],
    null_literal_kinds: &[],
    parameter_kinds: &[],
    class_kinds: &[],
    import_kinds: &["command"],
    block_scope_kinds: &["compound_statement"],
    break_kinds: &[],
    continue_kinds: &[],
    switch_kinds: &["case_statement"],
    case_kinds: &["case_item"],
    member_access_kinds: &[],
    binary_expression_kinds: &["binary_expression"],
    identifier_kinds: &["word", "variable_name"],
    unsafe_block_kinds: &[],
    defer_kinds: &[],
    spawn_kinds: &["subshell"],

    condition_field: "condition",
    consequence_field: "body",
    alternative_field: "alternative",
    body_field: "body",
    initializer_field: "value",
    left_field: "left",
    right_field: "right",
    name_field: "name",
    arguments_field: "argument",
    value_field: "value",
    operator_field: "operator",
    object_field: "",
    property_field: "",
    function_field: "name",
    parameters_field: "",
    return_type_field: "",
    type_field: "",
    handler_field: "",
    finalizer_field: "",
};
