use super::LanguageSemantics;

pub static ELIXIR_SEMANTICS: LanguageSemantics = LanguageSemantics {
    language: "elixir",

    function_def_kinds: &["call", "anonymous_function"],
    if_kinds: &["call"],
    loop_kinds: &[],
    variable_declaration_kinds: &["binary_operator"],
    assignment_kinds: &["binary_operator"],
    augmented_assignment_kinds: &[],
    return_kinds: &[],
    call_kinds: &["call", "dot"],
    try_catch_kinds: &["call"],
    throw_kinds: &["call"],
    string_literal_kinds: &["string", "charlist", "sigil"],
    numeric_literal_kinds: &["integer", "float"],
    boolean_literal_kinds: &["boolean"],
    null_literal_kinds: &["nil"],
    parameter_kinds: &["identifier"],
    class_kinds: &["call"],
    import_kinds: &["call"],
    block_scope_kinds: &["do_block"],
    break_kinds: &[],
    continue_kinds: &[],
    switch_kinds: &["call"],
    case_kinds: &["stab_clause"],
    member_access_kinds: &["dot"],
    binary_expression_kinds: &["binary_operator"],
    identifier_kinds: &["identifier", "atom"],
    unsafe_block_kinds: &[],
    defer_kinds: &[],
    spawn_kinds: &["call"],

    condition_field: "",
    consequence_field: "",
    alternative_field: "",
    body_field: "body",
    initializer_field: "right",
    left_field: "left",
    right_field: "right",
    name_field: "target",
    arguments_field: "arguments",
    value_field: "right",
    operator_field: "operator",
    object_field: "left",
    property_field: "right",
    function_field: "target",
    parameters_field: "arguments",
    return_type_field: "",
    type_field: "",
    handler_field: "",
    finalizer_field: "",
};
