use super::LanguageSemantics;

pub static SCALA_SEMANTICS: LanguageSemantics = LanguageSemantics {
    language: "scala",

    function_def_kinds: &[
        "function_definition",
        "function_declaration",
        "lambda_expression",
    ],
    if_kinds: &["if_expression"],
    loop_kinds: &["for_expression", "while_expression"],
    variable_declaration_kinds: &[
        "val_definition",
        "var_definition",
        "val_declaration",
        "var_declaration",
    ],
    assignment_kinds: &["assignment_expression"],
    augmented_assignment_kinds: &["assignment_expression"],
    return_kinds: &["return_expression"],
    call_kinds: &["call_expression"],
    try_catch_kinds: &["try_expression"],
    throw_kinds: &["throw_expression"],
    string_literal_kinds: &["string", "interpolated_string_expression"],
    numeric_literal_kinds: &["integer_literal", "floating_point_literal"],
    boolean_literal_kinds: &["boolean_literal"],
    null_literal_kinds: &["null_literal"],
    parameter_kinds: &["parameter"],
    class_kinds: &["class_definition", "trait_definition", "object_definition"],
    import_kinds: &["import_declaration"],
    block_scope_kinds: &["block", "template_body"],
    break_kinds: &[],
    continue_kinds: &[],
    switch_kinds: &["match_expression"],
    case_kinds: &["case_clause"],
    member_access_kinds: &["field_expression"],
    binary_expression_kinds: &["infix_expression"],
    identifier_kinds: &["identifier"],
    unsafe_block_kinds: &[],
    defer_kinds: &[],
    spawn_kinds: &[],

    condition_field: "condition",
    consequence_field: "consequence",
    alternative_field: "alternative",
    body_field: "body",
    initializer_field: "value",
    left_field: "left",
    right_field: "right",
    name_field: "name",
    arguments_field: "arguments",
    value_field: "value",
    operator_field: "operator",
    object_field: "object",
    property_field: "field",
    function_field: "function",
    parameters_field: "parameters",
    return_type_field: "return_type",
    type_field: "type",
    handler_field: "handler",
    finalizer_field: "finalizer",
};
