use super::LanguageSemantics;

pub static SWIFT_SEMANTICS: LanguageSemantics = LanguageSemantics {
    language: "swift",

    function_def_kinds: &["function_declaration", "lambda_literal"],
    if_kinds: &["if_statement"],
    loop_kinds: &["for_statement", "while_statement", "repeat_while_statement"],
    variable_declaration_kinds: &["property_declaration"],
    assignment_kinds: &["assignment"],
    augmented_assignment_kinds: &["assignment"],
    return_kinds: &["control_transfer_statement"],
    call_kinds: &["call_expression"],
    try_catch_kinds: &["do_statement"],
    throw_kinds: &["throw_statement"],
    string_literal_kinds: &["line_string_literal", "multi_line_string_literal"],
    numeric_literal_kinds: &["integer_literal", "real_literal"],
    boolean_literal_kinds: &["boolean_literal"],
    null_literal_kinds: &["nil"],
    parameter_kinds: &["parameter"],
    class_kinds: &[
        "class_declaration",
        "struct_declaration",
        "protocol_declaration",
        "enum_declaration",
    ],
    import_kinds: &["import_declaration"],
    block_scope_kinds: &["statements"],
    break_kinds: &["control_transfer_statement"],
    continue_kinds: &["control_transfer_statement"],
    switch_kinds: &["switch_statement"],
    case_kinds: &["switch_entry"],
    member_access_kinds: &["navigation_expression", "subscript_expression"],
    binary_expression_kinds: &["infix_expression"],
    identifier_kinds: &["simple_identifier"],
    unsafe_block_kinds: &[],
    defer_kinds: &["defer_statement"],
    spawn_kinds: &[],

    condition_field: "condition",
    consequence_field: "body",
    alternative_field: "alternative",
    body_field: "body",
    initializer_field: "value",
    left_field: "left",
    right_field: "right",
    name_field: "name",
    arguments_field: "arguments",
    value_field: "value",
    operator_field: "operator",
    object_field: "target",
    property_field: "suffix",
    function_field: "name",
    parameters_field: "parameters",
    return_type_field: "return_type",
    type_field: "type",
    handler_field: "catch_block",
    finalizer_field: "finally_clause",
};
